import '@fontsource-variable/geist';
import {useCallback, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import Viewer from './Viewer';
import type {components} from './generated';
import './style.css';

type Project = components['schemas']['ProjectOut'];
type Job = components['schemas']['JobOut'];
type ImageItem = components['schemas']['ImageOut'];
type Environment = Record<string, unknown>;
const api = async <T,>(path:string, init?:RequestInit):Promise<T> => { const r=await fetch(path,{headers:{'Content-Type':'application/json',...init?.headers},...init}); if(!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail); return r.json(); };
const label:Record<string,string>={queued:'Đang xếp hàng',running:'Đang chạy',succeeded:'Hoàn tất',failed:'Lỗi',cancelled:'Đã hủy',cancelling:'Đang hủy',interrupted:'Bị gián đoạn',timed_out:'Hết thời gian'};

function App(){
 const [capacity,setCapacity]=useState({max_frames:8,verified_levels:[] as number[],room_ready:false});
 const [autoBuild,setAutoBuild]=useState(true),[selectionMode,setSelectionMode]=useState<'auto'|'manual'>('auto'),[target,setTarget]=useState(32),[elapsed,setElapsed]=useState(0),[stage,setStage]=useState(''),[frameCount,setFrameCount]=useState(0);
 useEffect(()=>{api<typeof capacity>('/api/capabilities').then(setCapacity).catch(e=>setNotice(e.message))},[]);
 const [env,setEnv]=useState<Environment|null>(null),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[images,setImages]=useState<ImageItem[]>([]),[selected,setSelected]=useState<string[]>([]),[jobs,setJobs]=useState<Job[]>([]),[active,setActive]=useState<Job|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[path,setPath]=useState(''),[name,setName]=useState('ETH3D courtyard · 8 ảnh');
 const refresh=useCallback(async()=>{try{const [e,p]=await Promise.all([api<Environment>('/api/environment'),api<Project[]>('/api/projects')]);setEnv(e);setProjects(p);if(!project&&p[0])setProject(p[0])}catch(e){setNotice(e instanceof Error?e.message:'Không kết nối được API')}},[project]); useEffect(()=>{refresh()},[refresh]);
 const loadProject=useCallback(async()=>{if(!project)return;const [im,j]=await Promise.all([api<ImageItem[]>(`/api/projects/${project.id}/images`),api<Job[]>(`/api/projects/${project.id}/jobs`)]);setImages(im);setJobs(j);setActive(a=>a?.project_id===project.id?(j.find(x=>x.id===a.id)||a):(j.find(x=>['room','pipeline','train','geometry'].includes(x.kind))||null));setSelected(s=>s.filter(x=>im.some(i=>i.id===x)));},[project]); useEffect(()=>{loadProject()},[loadProject]);
 const doJob=async(kind:string,extra={})=>{if(!project)return;setLoading(true);try{const j=await api<Job>(`/api/projects/${project.id}/jobs`,{method:'POST',body:JSON.stringify({kind,images:selected,confidence:.5,iterations:10000,budget_minutes:30,selection_mode:selectionMode,target_frames:target,...extra})});setActive(j);setNotice('Job đã bắt đầu');await loadProject()}catch(e){setNotice(e instanceof Error?e.message:'Không tạo được job')}finally{setLoading(false)}};
 useEffect(()=>{if(!active||!['queued','running','cancelling'].includes(active.status))return;const es=new EventSource(`/api/jobs/${active.id}/events`);es.onmessage=e=>{try{const x=JSON.parse(e.data);setNotice(x.message||'Đang chạy');setElapsed(x.elapsed_seconds||0);setStage(x.stage||'');setFrameCount(x.frame_count||0)}catch{}};es.addEventListener('done',()=>{es.close();loadProject().then(()=>api<Job>(`/api/jobs/${active.id}`).then(setActive))});return()=>es.close()},[active,loadProject]);
 const envItems=useMemo(()=>env?[['MPS',(env.mps as {ok:boolean})?.ok],['Metal',(env.metal as {ok:boolean})?.ok],['VGGT model',(env.model as {ok:boolean})?.ok],['OpenSplat Metal',(env.opensplat as {ok:boolean})?.ok]]:[],[env]);
 return <main><header><div><span className="eyebrow">LOCAL · M1 MAX</span><h1>Courtyard Studio</h1></div><div className="checks">{envItems.map(([n,ok])=><span key={String(n)} className={ok?'ok':'bad'}>{String(n)}: {ok?'sẵn sàng':'chưa sẵn sàng'}</span>)}</div></header>
 <div className="layout"><aside><h2>Nguồn ảnh</h2><label>Project<select value={project?.id||''} onChange={e=>setProject(projects.find(p=>p.id===e.target.value)||null)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Tên project<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={loading} onClick={async()=>{try{const p=await api<Project>('/api/projects',{method:'POST',body:JSON.stringify({name})});setProject(p);setImages([]);setSelected([])}catch(e){setNotice(String(e))}}}>Tạo project</button><button disabled={!project||loading} onClick={()=>doJob('courtyard')}>Tải ETH3D courtyard</button><label>Thư mục ảnh local<input placeholder="/Users/.../images" value={path} onChange={e=>setPath(e.target.value)}/></label><button disabled={!path||!project||loading} onClick={()=>doJob('import',{path})}>Nhập thư mục</button><label><input type="checkbox" checked={autoBuild} onChange={e=>setAutoBuild(e.target.checked)}/>Upload và dựng phòng 3D</label><label>Video local<input type="file" accept="video/mp4,video/quicktime,video/x-matroska,video/webm,video/x-msvideo" onChange={async e=>{const file=e.target.files?.[0];if(!file||!project)return;setLoading(true);try{const form=new FormData();form.append('file',file);const j=await fetch(`/api/projects/${project.id}/video?fps=1&create_project_if_occupied=true&reconstruct=${autoBuild}&target_frames=${target}`,{method:'POST',body:form}).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail);return r.json() as Promise<Job>});const updated=await api<Project[]>('/api/projects');setProjects(updated);setProject(updated.find(p=>p.id===j.project_id)||null);setImages([]);setSelected([]);setJobs([j]);setActive(j);setNotice(autoBuild?'Đã upload; đang dựng phòng 3D':'Đã upload; đang trích ảnh')}catch(err){setNotice(err instanceof Error?err.message:'Không gửi được video')}finally{setLoading(false)}}}/></label><p className="muted">Lấy tối đa 1.200 ảnh xuyên suốt video. Tự chọn 32 ảnh rõ, bổ sung tới 48/64 nếu thiếu liên kết. Ngân sách 30 phút từ khi upload xong. Nếu project đã có ảnh, Studio tự tạo project mới.</p></aside>
 <section className="work"><div className="section-head"><div><span className="eyebrow">{project?.name||'Chưa chọn project'}</span><h2>Timeline ảnh</h2></div><span>{selected.length}/{capacity.max_frames}</span></div>{images.length===0?<div className="empty">Tải courtyard hoặc nhập thư mục ảnh để hiện thumbnail.</div>:<div className="gallery">{images.map(im=><button aria-pressed={selected.includes(im.id)} className="image" key={im.id} onClick={()=>setSelected(s=>s.includes(im.id)?s.filter(x=>x!==im.id):s.length<capacity.max_frames?[...s,im.id]:s)}><img src={`/api/projects/${project!.id}/files/${im.thumbnail}`} alt={im.name}/><span>{im.timestamp_seconds != null ? `${im.timestamp_seconds.toFixed(1)}s · ` : ''}{im.name}</span></button>)}</div>}<label>Chọn ảnh<select value={selectionMode} onChange={e=>setSelectionMode(e.target.value as 'auto'|'manual')}><option value="auto">Tự động theo toàn thời lượng</option><option value="manual">Thủ công · thêm/bỏ ảnh trên timeline</option></select></label><label>Số ảnh mục tiêu<select value={target} onChange={e=>setTarget(Number(e.target.value))}>{[8,16,32,48,64].map(n=><option key={n} value={n} disabled={n>capacity.max_frames}>{n} ảnh{n>capacity.max_frames?' · chưa kiểm chứng MPS':''}</option>)}</select></label><p className="muted">MPS đã kiểm chứng tối đa {capacity.max_frames} ảnh. Các vùng thiếu góc nhìn hoặc bị che có thể không tái dựng được.</p><div className="actions"><button className="primary" disabled={(selectionMode==='manual'?selected.length<2:selected.length===0&&images.length<2)||loading||(selectionMode==='auto'&&target>capacity.max_frames)} onClick={()=>doJob('geometry')}>Chạy VGGT MPS → Geometry</button><button disabled={!jobs.some(j=>j.kind==='geometry'&&j.status==='succeeded')||loading} onClick={()=>{const j=jobs.find(j=>j.kind==='geometry'&&j.status==='succeeded');if(j)doJob('train',{geometry_job:j.id})}}>Train OpenSplat Metal</button><button disabled={(selectionMode==='manual'?selected.length<2:selected.length===0&&images.length<2)||loading||(selectionMode==='auto'&&target>capacity.max_frames)} onClick={()=>doJob('pipeline')}>Chạy toàn pipeline</button></div><p aria-live="polite" className="notice">{notice}</p>
 <p>{stage} · {frameCount} ảnh · {Math.floor(elapsed/60)} phút {Math.floor(elapsed%60)} giây</p><h2>Runs</h2><div className="runs">{jobs.map(j=><button key={j.id} onClick={()=>setActive(j)} className={active?.id===j.id?'selected':''}><b>{j.kind}</b><span className={`status ${j.status}`}>{label[j.status]||j.status}</span><small>{new Date(j.created*1000).toLocaleString('vi-VN')}</small></button>)}</div>{active&&<div className="run-detail"><div><h2>{active.kind} · {label[active.status]}</h2>{active.error&&<p className="error">{active.error}</p>}{['room','geometry','pipeline'].includes(active.kind)&&<button onClick={async()=>{try{const r=await api<{images:ImageItem[]}>(`/api/jobs/${active.id}/artifacts/selection.json`);setSelected(r.images.map(i=>i.id));setSelectionMode('manual')}catch(e){setNotice(String(e))}}}>Xem và sửa ảnh đã chọn</button>}<a href={`/api/jobs/${active.id}/artifacts`} target="_blank">Danh sách artifact</a>{['queued','running','cancelling'].includes(active.status)&&<button onClick={()=>api<Job>(`/api/jobs/${active.id}/cancel`,{method:'POST'}).then(setActive).catch(e=>setNotice(e.message))}>Hủy job</button>}</div>{['room','geometry','pipeline','train'].includes(active.kind)&&<Viewer job={active} paused={jobs.some(j=>['queued','running','cancelling'].includes(j.status)&&['room','geometry','pipeline','train'].includes(j.kind))}/>}</div>}</section></div></main> }
createRoot(document.getElementById('root')!).render(<App/>);
